language: node_js
node_js:
  - "0.10"
script: deps/bats/bin/bats test --tap
cache:
  directories:
    - deps
    - node_modules
notifications:
  email:
    on_success: change
    on_failure: always
after_sucess:
  - npm install brief && node_modules/.bin/brief
