language: node_js
node_js:
    - "0.10"
script: make test
env:
    - BATS_OPTS="--tap"
cache:
	directories:
	- scripts/bats
notifications:
  email:
    on_success: change
    on_failure: always
after_sucess:
    - npm install brief
    - node_modules/.bin/brief
