#!/bin/sh
# Script to launch dmenu with colors matching IR_Black theme
# Author: Vic Fryzel
# http://github.com/vicfryzel/xmonad-config

/usr/bin/dmenu_run -fn 'dina-8' -nb '#000000' -nf '#FFFFFF' -sb '#7C7C7C' -sf '#CEFFAC'
