#!/usr/bin/env python

# name: htpasswd
# desc: creates basic auth compatible username/pass
# usage: htpasswd.py user password >> pasword_file

import crypt
import sys

if len(sys.argv) == 3:
    print("%s:%s" % (sys.argv[1], crypt.crypt(sys.argv[2], sys.argv[2])))
