#!/usr/bin/env python

# name: rm_pyc
# desc: removes all .pyc files in a directory recursively

import os
import sys

def rm_pyc(f):
    if f[-3:] == 'pyc':
        print '- ' + f
        os.remove(f)

def walk_dir(path):
    for root, dirs, files in os.walk(path):
        for name in files:
            rm_pyc(os.path.join(root, name))

if __name__ == "__main__":
    if len(sys.argv) > 1:
        walk_dir(sys.argv[1])
    else:
        walk_dir(os.getcwd())
