# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "plist", "~>3.1.0"
gem "logging", "~>1.8.0"

gem "rdoc", "~>3.10", :group => [:development, :test]
gem "hoe", "~>3.5", :group => [:development, :test]
gem "rspec", "~>2.13", :group => [:development, :test]

# vim: syntax=ruby
