zeesh_plugins=(
    upstart
    autocomplete
    vi-mode
    vi-visual-mode
    osx
    python
    django
    virtualenv
    clojure
    haskell
    mercurial
    git
    vcs-info
    syntax-highlighting
    history-substring-search
    theme
)
source ~/.zsh/zeesh.zsh

export ZEESH_THEME_NORMAL_CHAR='\n⊙'
export ZEESH_THEME_VISUAL_CHAR='\n⊡'
export ZEESH_THEME_INSERT_CHAR='\n›'
export ZEESH_THEME_PROMPT_CHAR=

alias gist=jist
alias git='noglob hub'
alias http='noglob http'
alias utc='date -u'
alias v=vim

export PATH=~/.bin:~/.ellipsis/bin:/usr/local/share/npm/bin:$PATH
export NODE_PATH=/usr/local/share/npm/lib/node_modules

compctl -k "(push pull status)" ellipsis

if [ -e ~/.private/zsh ]; then
    source ~/.private/zsh
fi

alias sl=ls
export GIT=/usr/local/bin/git
zstyle ':vcs_info:git:*:-all-' command $GIT
alias ag="ag -a -S --color-match='30;31' --color-line-number='31;35' --color-path='31;34'"
