zeesh_plugins=(
    upstart
    autocomplete
    vi-mode
    vi-visual-mode
    osx
    python
    django
    virtualenv
    haskell
    mercurial
    git
    vcs-info
    syntax-highlighting
    history-substring-search
    theme
)
source ~/.zsh/zeesh.zsh

export ZEESH_THEME_NORMAL_CHAR='\n⊙'
export ZEESH_THEME_VISUAL_CHAR='\n⊡'
export ZEESH_THEME_INSERT_CHAR='\n›'
export ZEESH_THEME_PROMPT_CHAR=

alias git='noglob hub'
alias http='noglob http'
alias utc='date -u'
alias v=vim

export PATH=~/.bin:~/.ellipsis/bin:$PATH

compctl -k "(push pull status)" ellipsis

if [ -e ~/.private/zsh ]; then
    source ~/.private/zsh
fi

alias sl=ls
zstyle ':vcs_info:git:*:-all-' command git
