zeesh_plugins=(
    osx
    vi-mode
    python
    django
    virtualenv
    haskell
    mercurial
    git
    vcs-info
    syntax-highlighting
    history-substring-search
    theme
    upstart
    autocomplete
)
source ~/.zsh/zeesh.zsh

export ZEESH_THEME_NORMAL_CHAR='\n⊙'
export ZEESH_THEME_VISUAL_CHAR='\n⊡'
export ZEESH_THEME_INSERT_CHAR='\n›'
export ZEESH_THEME_PROMPT_CHAR=

alias git='noglob hub'
alias http='noglob http'
alias utc='date -u'
alias v=vim

export PATH=~/.bin:~/.ellipsis/bin:$PATH

compctl -k "(push pull status)" ellipsis

if [ -e ~/.private/zsh ]; then
    source ~/.private/zsh
fi

alias sl=ls
alias clj='lein repl'

###-begin-npm-completion-###
#
# npm command completion script
#
# Installation: npm completion >> ~/.bashrc  (or ~/.zshrc)
# Or, maybe: npm completion > /usr/local/etc/bash_completion.d/npm
#

COMP_WORDBREAKS=${COMP_WORDBREAKS/=/}
COMP_WORDBREAKS=${COMP_WORDBREAKS/@/}
export COMP_WORDBREAKS

if type complete &>/dev/null; then
  _npm_completion () {
    local si="$IFS"
    IFS=$'\n' COMPREPLY=($(COMP_CWORD="$COMP_CWORD" \
                           COMP_LINE="$COMP_LINE" \
                           COMP_POINT="$COMP_POINT" \
                           npm completion -- "${COMP_WORDS[@]}" \
                           2>/dev/null)) || return $?
    IFS="$si"
  }
  complete -F _npm_completion npm
elif type compdef &>/dev/null; then
  _npm_completion() {
    si=$IFS
    compadd -- $(COMP_CWORD=$((CURRENT-1)) \
                 COMP_LINE=$BUFFER \
                 COMP_POINT=0 \
                 npm completion -- "${words[@]}" \
                 2>/dev/null)
    IFS=$si
  }
  compdef _npm_completion npm
elif type compctl &>/dev/null; then
  _npm_completion () {
    local cword line point words si
    read -Ac words
    read -cn cword
    let cword-=1
    read -l line
    read -ln point
    si="$IFS"
    IFS=$'\n' reply=($(COMP_CWORD="$cword" \
                       COMP_LINE="$line" \
                       COMP_POINT="$point" \
                       npm completion -- "${words[@]}" \
                       2>/dev/null)) || return $?
    IFS="$si"
  }
  compctl -K _npm_completion npm
fi
###-end-npm-completion-###

zstyle ':vcs_info:git:*:-all-' command /usr/local/bin/git
export GOPATH=$HOME/go
export PATH=$PATH:/usr/local/Cellar/go/1.2/libexec/bin:/usr/local/cuda/bin:$GOPATH/bin
alias hd='noglob hoodoo'
alias ack=ag
alias cask='brew cask'

if [ -f /usr/loca/opt/autoenv/activate.sh ]; then
    source /usr/local/opt/autoenv/activate.sh
fi

alias cake=shortcake
