#!/bin/sh

# push changes back to repo

basedir="$( cd -P "$( dirname "$0" )" && pwd )"/..
cachedir=~/.cache/dotfiles/push

# clear cachedir
mkdir -p $cachedir
rm -rf $cachedir/*

trap "exit 0" SIGINT

# enable job control
set -m

push(){
    if [ -d ".hg" ]; then
        echo -e "\033[1mpushing $1\033[0m" | sed 's/\-e //' > $cachedir/$1
        hg ci -q
        hg push >> $cachedir/$1 2>&1 &
    else
        git push
    fi
}

cd $basedir
push dotfiles

for dir in `find . -mindepth 2 -maxdepth 2 \
    -name '.hg' -o \
    -name '.git' | cut -d / -f 2 | sort`; do

    cd $basedir/$dir
    push $dir
done

# wait for parallel jobs to finish
if [ "`uname`" != "FreeBSD" ]; then
    while [ 1 ]; do fg &> /dev/null; [ $? == 1 ] && break; done
fi

# print output
cat $cachedir/*
