#!/bin/sh

basedir="$( cd -P "$( dirname "$0" )" && pwd )"/..

cd $basedir
if [ -d ".hg" ]; then
    hg ci
    hg push
else
    git commit -a
    git push
fi

for dir in `find . \
    -mindepth 2 -maxdepth 2 -name '.hg' -o \
    -mindepth 2 -maxdepth 2 -name '.git' | cut -d / -f 2`; do

    cd $basedir/$dir
    if [ -d ".hg" ]; then
        hg ci
        hg push
    else
        git commit -a
        git push
    fi
done
