#!/bin/sh

# updates repos

basedir="$( cd -P "$( dirname "$0" )" && pwd )"/..
cachedir=~/.cache/dotfiles/up

# clear cachedir
mkdir -p $cachedir
rm -rf $cachedir/*

trap "exit 0" SIGINT

# enable job control
set -m

update(){
    if [ -d ".hg" ]; then
        echo -e "\033[1mupdating $1\033[0m" | sed 's/\-e //' > $cachedir/$1
        hg fetch >> $cachedir/$1 2>&1 &
    else
        echo -e "\033[1mupdating $1\033[0m" | sed 's/\-e //' > $cachedir/$1
        git pull >> $cachedir/$1 2>&1 &
    fi
}

cd $basedir
update dotfiles

for dir in `find . -mindepth 2 -maxdepth 2 -name '.hg' -o -name '.git' | cut -d / -f 2 | sort`; do
    cd $basedir/$dir
    update $dir
done

# wait for parallel jobs to finish
if [ "`uname`" != "FreeBSD" ]; then
    while [ 1 ]; do fg &> /dev/null; [ $? == 1 ] && break; done
fi

# print output
cat $cachedir/*
